// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

export const hasSupabaseEnvConfiguration = (url?: string, publishableKey?: string) =>
  Boolean(url && publishableKey);

export const isSupabaseConfigured = hasSupabaseEnvConfiguration(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);

export const missingSupabaseConfigMessage =
  "Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to your local .env file.";

const createMissingConfigError = () => new Error(missingSupabaseConfigMessage);

const createAwaitableBuilder = () => {
  const response = {
    data: null,
    error: createMissingConfigError(),
    count: null,
    status: 503,
    statusText: "Supabase not configured",
  };
  const resolved = Promise.resolve(response);

  const builder = new Proxy(
    {},
    {
      get(_target, prop) {
        if (prop === "then") return resolved.then.bind(resolved);
        if (prop === "catch") return resolved.catch.bind(resolved);
        if (prop === "finally") return resolved.finally.bind(resolved);
        return () => builder;
      },
    },
  );

  return builder;
};

const createFallbackClient = (): SupabaseClient<Database> =>
  ({
    auth: {
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      getSession: async () => ({
        data: { session: null },
        error: createMissingConfigError(),
      }),
      getUser: async () => ({
        data: { user: null },
        error: createMissingConfigError(),
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: createMissingConfigError(),
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: createMissingConfigError(),
      }),
      signOut: async () => ({
        error: createMissingConfigError(),
      }),
      resetPasswordForEmail: async () => ({
        data: {},
        error: createMissingConfigError(),
      }),
      updateUser: async () => ({
        data: { user: null },
        error: createMissingConfigError(),
      }),
      setSession: async () => ({
        data: { session: null, user: null },
        error: createMissingConfigError(),
      }),
      mfa: {
        getAuthenticatorAssuranceLevel: async () => ({
          data: null,
          error: createMissingConfigError(),
        }),
        listFactors: async () => ({
          data: { all: [], totp: [], phone: [] },
          error: createMissingConfigError(),
        }),
        challenge: async () => ({
          data: null,
          error: createMissingConfigError(),
        }),
        verify: async () => ({
          data: null,
          error: createMissingConfigError(),
        }),
        enroll: async () => ({
          data: null,
          error: createMissingConfigError(),
        }),
        unenroll: async () => ({
          data: null,
          error: createMissingConfigError(),
        }),
      },
    },
    from: () => createAwaitableBuilder(),
    storage: {
      from: () => createAwaitableBuilder(),
    },
    functions: {
      invoke: async () => ({
        data: null,
        error: createMissingConfigError(),
      }),
    },
  }) as unknown as SupabaseClient<Database>;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createFallbackClient();